### ISSUE TITLE
Add to F-Droid

### ISSUE THREAD

**Issue by licaon-kter** [talkback-foss-team/talkback-foss#80]
How far is 14.1 from release?

I was looking at https://github.com/talkback-foss-team/talkback-foss/releases/tag/v13.0.0.473912301-f02 and testing reproducibility and the differences are huge

draft recipe **metadata/app.talkbackfoss.yml**
```
License: Unknown
SourceCode: https://github.com/talkback-foss-team/talkback-foss
IssueTracker: https://github.com/talkback-foss-team/talkback-foss/issues

RepoType: git
Repo: https://github.com/talkback-foss-team/talkback-foss
Binaries: https://github.com/talkback-foss-team/talkback-foss/releases/download/v13.0.0.473912301-f02/talkback-foss-phone-release-signed.apk

Builds:
  - versionName: 13.0-f02
    versionCode: 3
    commit: b480c47f1ee4a48aa79ed8c5f71d25d55f28a022
    gradle:
      - phone
    prebuild: sed -i -e '/libs.wear/d' shared.gradle
    scandelete:
      - braille

AllowedAPKSigningKeys: 42b1f7f159e2e17b48f8e9cb67100617728c74bb8a77000616e913cecd53daa0

AutoUpdateMode: Version
UpdateCheckMode: Tags
CurrentVersion: '14.1'
CurrentVersionCode: 3
```

diff:
```
Binary files /tmp/tmpvsjlpgj5/unsigned_binaries_app.talkbackfoss_3.binary/content/AndroidManifest.xml and /tmp/tmpvsjlpgj5/unsigned_app.talkbackfoss_3/content/AndroidManifest.xml differ
Binary files /tmp/tmpvsjlpgj5/unsigned_binaries_app.talkbackfoss_3.binary/content/assets/dexopt/baseline.prof and /tmp/tmpvsjlpgj5/unsigned_app.talkbackfoss_3/content/assets/dexopt/baseline.prof differ
Binary files /tmp/tmpvsjlpgj5/unsigned_binaries_app.talkbackfoss_3.binary/content/assets/dexopt/baseline.profm and /tmp/tmpvsjlpgj5/unsigned_app.talkbackfoss_3/content/assets/dexopt/baseline.profm differ
Binary files /tmp/tmpvsjlpgj5/unsigned_binaries_app.talkbackfoss_3.binary/content/classes.dex and /tmp/tmpvsjlpgj5/unsigned_app.talkbackfoss_3/content/classes.dex differ
Binary files /tmp/tmpvsjlpgj5/unsigned_binaries_app.talkbackfoss_3.binary/content/classes2.dex and /tmp/tmpvsjlpgj5/unsigned_app.talkbackfoss_3/content/classes2.dex differ
Binary files /tmp/tmpvsjlpgj5/unsigned_binaries_app.talkbackfoss_3.binary/content/classes3.dex and /tmp/tmpvsjlpgj5/unsigned_app.talkbackfoss_3/content/classes3.dex differ
Binary files /tmp/tmpvsjlpgj5/unsigned_binaries_app.talkbackfoss_3.binary/content/lib/arm64-v8a/libbrlttywrap.so and /tmp/tmpvsjlpgj5/unsigned_app.talkbackfoss_3/content/lib/arm64-v8a/libbrlttywrap.so differ
Binary files /tmp/tmpvsjlpgj5/unsigned_binaries_app.talkbackfoss_3.binary/content/lib/arm64-v8a/libc++_shared.so and /tmp/tmpvsjlpgj5/unsigned_app.talkbackfoss_3/content/lib/arm64-v8a/libc++_shared.so differ
Binary files /tmp/tmpvsjlpgj5/unsigned_binaries_app.talkbackfoss_3.binary/content/lib/arm64-v8a/liblouis.so and /tmp/tmpvsjlpgj5/unsigned_app.talkbackfoss_3/content/lib/arm64-v8a/liblouis.so differ
Binary files /tmp/tmpvsjlpgj5/unsigned_binaries_app.talkbackfoss_3.binary/content/lib/arm64-v8a/liblouiswrap.so and /tmp/tmpvsjlpgj5/unsigned_app.talkbackfoss_3/content/lib/arm64-v8a/liblouiswrap.so differ
Binary files /tmp/tmpvsjlpgj5/unsigned_binaries_app.talkbackfoss_3.binary/content/lib/armeabi-v7a/libbrlttywrap.so and /tmp/tmpvsjlpgj5/unsigned_app.talkbackfoss_3/content/lib/armeabi-v7a/libbrlttywrap.so differ
Binary files /tmp/tmpvsjlpgj5/unsigned_binaries_app.talkbackfoss_3.binary/content/lib/armeabi-v7a/libc++_shared.so and /tmp/tmpvsjlpgj5/unsigned_app.talkbackfoss_3/content/lib/armeabi-v7a/libc++_shared.so differ
Binary files /tmp/tmpvsjlpgj5/unsigned_binaries_app.talkbackfoss_3.binary/content/lib/armeabi-v7a/liblouis.so and /tmp/tmpvsjlpgj5/unsigned_app.talkbackfoss_3/content/lib/armeabi-v7a/liblouis.so differ
Binary files /tmp/tmpvsjlpgj5/unsigned_binaries_app.talkbackfoss_3.binary/content/lib/armeabi-v7a/liblouiswrap.so and /tmp/tmpvsjlpgj5/unsigned_app.talkbackfoss_3/content/lib/armeabi-v7a/liblouiswrap.so differ
Binary files /tmp/tmpvsjlpgj5/unsigned_binaries_app.talkbackfoss_3.binary/content/lib/x86/libbrlttywrap.so and /tmp/tmpvsjlpgj5/unsigned_app.talkbackfoss_3/content/lib/x86/libbrlttywrap.so differ
Binary files /tmp/tmpvsjlpgj5/unsigned_binaries_app.talkbackfoss_3.binary/content/lib/x86/libc++_shared.so and /tmp/tmpvsjlpgj5/unsigned_app.talkbackfoss_3/content/lib/x86/libc++_shared.so differ
Binary files /tmp/tmpvsjlpgj5/unsigned_binaries_app.talkbackfoss_3.binary/content/lib/x86/liblouis.so and /tmp/tmpvsjlpgj5/unsigned_app.talkbackfoss_3/content/lib/x86/liblouis.so differ
Binary files /tmp/tmpvsjlpgj5/unsigned_binaries_app.talkbackfoss_3.binary/content/lib/x86/liblouiswrap.so and /tmp/tmpvsjlpgj5/unsigned_app.talkbackfoss_3/content/lib/x86/liblouiswrap.so differ
Binary files /tmp/tmpvsjlpgj5/unsigned_binaries_app.talkbackfoss_3.binary/content/lib/x86_64/libbrlttywrap.so and /tmp/tmpvsjlpgj5/unsigned_app.talkbackfoss_3/content/lib/x86_64/libbrlttywrap.so differ
Binary files /tmp/tmpvsjlpgj5/unsigned_binaries_app.talkbackfoss_3.binary/content/lib/x86_64/libc++_shared.so and /tmp/tmpvsjlpgj5/unsigned_app.talkbackfoss_3/content/lib/x86_64/libc++_shared.so differ
Binary files /tmp/tmpvsjlpgj5/unsigned_binaries_app.talkbackfoss_3.binary/content/lib/x86_64/liblouis.so and /tmp/tmpvsjlpgj5/unsigned_app.talkbackfoss_3/content/lib/x86_64/liblouis.so differ
Binary files /tmp/tmpvsjlpgj5/unsigned_binaries_app.talkbackfoss_3.binary/content/lib/x86_64/liblouiswrap.so and /tmp/tmpvsjlpgj5/unsigned_app.talkbackfoss_3/content/lib/x86_64/liblouiswrap.so differ
Binary files /tmp/tmpvsjlpgj5/unsigned_binaries_app.talkbackfoss_3.binary/content/res/-1.xml and /tmp/tmpvsjlpgj5/unsigned_app.talkbackfoss_3/content/res/-1.xml differ
Binary files /tmp/tmpvsjlpgj5/unsigned_binaries_app.talkbackfoss_3.binary/content/res/-5.xml and /tmp/tmpvsjlpgj5/unsigned_app.talkbackfoss_3/content/res/-5.xml differ
Binary files /tmp/tmpvsjlpgj5/unsigned_binaries_app.talkbackfoss_3.binary/content/res/-7.xml and /tmp/tmpvsjlpgj5/unsigned_app.talkbackfoss_3/content/res/-7.xml differ
Only in /tmp/tmpvsjlpgj5/unsigned_binaries_app.talkbackfoss_3.binary/content/res: -8.xml
Binary files /tmp/tmpvsjlpgj5/unsigned_binaries_app.talkbackfoss_3.binary/content/res/-Q.xml and /tmp/tmpvsjlpgj5/unsigned_app.talkbackfoss_3/content/res/-Q.xml differ
Only in /tmp/tmpvsjlpgj5/unsigned_binaries_app.talkbackfoss_3.binary/content/res: 0D.png
Binary files /tmp/tmpvsjlpgj5/unsigned_binaries_app.talkbackfoss_3.binary/content/res/0E.xml and /tmp/tmpvsjlpgj5/unsigned_app.talkbackfoss_3/content/res/0E.xml differ
Binary files /tmp/tmpvsjlpgj5/unsigned_binaries_app.talkbackfoss_3.binary/content/res/0G.xml and /tmp/tmpvsjlpgj5/unsigned_app.talkbackfoss_3/content/res/0G.xml differ
Binary files /tmp/tmpvsjlpgj5/unsigned_binaries_app.talkbackfoss_3.binary/content/res/0M.xml and /tmp/tmpvsjlpgj5/unsigned_app.talkbackfoss_3/content/res/0M.xml differ
Binary files /tmp/tmpvsjlpgj5/unsigned_binaries_app.talkbackfoss_3.binary/content/res/0M1.xml and /tmp/tmpvsjlpgj5/unsigned_app.talkbackfoss_3/content/res/0M1.xml differ
Only in /tmp/tmpvsjlpgj5/unsigned_binaries_app.talkbackfoss_3.binary/content/res: 0M2.xml
Binary files /tmp/tmpvsjlpgj5/unsigned_binaries_app.talkbackfoss_3.binary/content/res/0R.xml and /tmp/tmpvsjlpgj5/unsigned_app.talkbackfoss_3/content/res/0R.xml differ
Binary files /tmp/tmpvsjlpgj5/unsigned_binaries_app.talkbackfoss_3.binary/content/res/0S.xml and /tmp/tmpvsjlpgj5/unsigned_app.talkbackfoss_3/content/res/0S.xml differ
...
more
```
